# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Counters' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'IQKeyboardManagerSwift'
  pod 'ReachabilitySwift'
  pod 'SwiftLint'

  # Pods for Counters

  target 'CountersTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CountersUITests' do
    # Pods for testing
  end

end
